import type {
  Application,
  ApplicationDocument,
  AuditLog,
  Avenant,
  Deal,
  DealDocument,
  DealRequirement,
  DealStage,
  EvaluationCriterion,
  ExecutionTracking,
  Notification,
  Operator,
  OperatorDocument,
  Organization,
  Report,
  RiskAlert,
  TransparencyScore,
} from "@/types/domain";

export const organizations: Organization[] = [
  {
    id: "org-health-ministry",
    name: "وزارة الصحة",
    type: "institution",
    sector: "الصحة",
    address: "الجزائر العاصمة",
    phone: "+213 21 00 00 00",
    email: "procurement@sante.gov.dz",
    status: "active",
  },
  {
    id: "org-health-projects",
    name: "مديرية المشاريع الصحية",
    type: "directorate",
    sector: "المشاريع العمومية",
    address: "حيدرة، الجزائر",
    phone: "+213 21 11 11 11",
    email: "projects@sante.gov.dz",
    status: "active",
  },
];

export const operators: Operator[] = [
  {
    id: "op-future",
    name: "شركة المستقبل للإنشاءات والمقاولات",
    entityType: "company",
    registrationNumber: "RC-16-2020-B-45821",
    taxNumber: "000216458210032",
    sector: "البناء والأشغال العمومية",
    specialization: "منشآت صحية ومرافق عمومية",
    address: "باب الزوار، الجزائر",
    region: "الجزائر",
    phone: "+213 560 00 00 01",
    email: "contact@future-build.dz",
    status: "active",
    foundedAt: "2015-03-15",
    capital: 260000000,
    employeeCount: 180,
    companySize: "large",
    classification: "درجة 7",
    performanceScore: 86,
    riskScore: 22,
    winRate: 34,
    previousParticipations: 18,
    previousWins: 6,
    validDocumentsPercent: 96,
  },
  {
    id: "op-modern-build",
    name: "مؤسسة البناء المتطور",
    entityType: "company",
    registrationNumber: "RC-31-2018-A-12008",
    taxNumber: "000231120080041",
    sector: "البناء والأشغال العمومية",
    specialization: "هياكل خرسانية وتجهيزات تقنية",
    address: "وهران",
    region: "وهران",
    phone: "+213 560 00 00 02",
    email: "office@modern-build.dz",
    status: "active",
    foundedAt: "2012-10-01",
    capital: 180000000,
    employeeCount: 115,
    companySize: "medium",
    classification: "درجة 6",
    performanceScore: 78,
    riskScore: 36,
    winRate: 21,
    previousParticipations: 14,
    previousWins: 3,
    validDocumentsPercent: 88,
  },
  {
    id: "op-inmaa",
    name: "شركة الإنماء للمشاريع",
    entityType: "company",
    registrationNumber: "RC-09-2019-B-88910",
    taxNumber: "000209889100023",
    sector: "التجهيزات الطبية",
    specialization: "توريد وتركيب أجهزة طبية",
    address: "البليدة",
    region: "البليدة",
    phone: "+213 560 00 00 03",
    email: "commercial@inmaa-med.dz",
    status: "active",
    foundedAt: "2017-06-21",
    capital: 95000000,
    employeeCount: 64,
    companySize: "medium",
    classification: "معتمد",
    performanceScore: 82,
    riskScore: 28,
    winRate: 29,
    previousParticipations: 17,
    previousWins: 5,
    validDocumentsPercent: 91,
  },
  {
    id: "op-rawad",
    name: "مؤسسة الرواد المتحدة",
    entityType: "company",
    registrationNumber: "RC-25-2017-A-55109",
    taxNumber: "000225551090018",
    sector: "الخدمات والصيانة",
    specialization: "تشغيل وصيانة شبكات المياه",
    address: "قسنطينة",
    region: "قسنطينة",
    phone: "+213 560 00 00 04",
    email: "info@rawad-services.dz",
    status: "under_review",
    foundedAt: "2010-01-12",
    capital: 120000000,
    employeeCount: 130,
    companySize: "medium",
    classification: "درجة 5",
    performanceScore: 69,
    riskScore: 58,
    winRate: 42,
    previousParticipations: 19,
    previousWins: 8,
    validDocumentsPercent: 76,
  },
  {
    id: "op-ahd",
    name: "مؤسسة العهد للمقاولات",
    entityType: "company",
    registrationNumber: "RC-16-2022-B-30041",
    taxNumber: "000216300410011",
    sector: "البناء والأشغال العمومية",
    specialization: "تهيئة وتجديد",
    address: "المدية",
    region: "المدية",
    phone: "+213 560 00 00 05",
    email: "contact@ahd-contracting.dz",
    status: "active",
    foundedAt: "2020-11-02",
    capital: 45000000,
    employeeCount: 38,
    companySize: "small",
    classification: "درجة 3",
    performanceScore: 61,
    riskScore: 47,
    winRate: 12,
    previousParticipations: 8,
    previousWins: 1,
    validDocumentsPercent: 82,
  },
  {
    id: "op-haditha",
    name: "شركة الإنشاءات الحديثة",
    entityType: "company",
    registrationNumber: "RC-35-2014-B-77742",
    taxNumber: "000235777420055",
    sector: "البناء والأشغال العمومية",
    specialization: "منشآت كبرى وجسور",
    address: "بومرداس",
    region: "بومرداس",
    phone: "+213 560 00 00 06",
    email: "tenders@haditha.dz",
    status: "active",
    foundedAt: "2008-05-04",
    capital: 420000000,
    employeeCount: 260,
    companySize: "large",
    classification: "درجة 8",
    performanceScore: 91,
    riskScore: 18,
    winRate: 31,
    previousParticipations: 29,
    previousWins: 9,
    validDocumentsPercent: 98,
  },
];

export const deals: Deal[] = [
  {
    id: "deal-health-center",
    organizationId: "org-health-projects",
    reference: "2025/178",
    title: "إنجاز مركز صحي متعدد الخدمات",
    description: "إنجاز وتجهيز مركز صحي جديد مع الربط بالشبكات التقنية والتهيئة الخارجية.",
    type: "أشغال",
    sector: "البناء والأشغال العمومية",
    region: "الجزائر",
    estimatedValue: 420000000,
    currency: "DZD",
    status: "technical_evaluation",
    publishedAt: "2025-04-01",
    submissionDeadline: "2025-05-15",
    openingDate: "2025-05-16",
    evaluationStartDate: "2025-05-20",
    awardDate: "2025-07-12",
    executionStartDate: "2025-08-01",
    executionEndDate: "2026-08-01",
    isPublic: true,
    aiEnabled: false,
    smartMatchingEnabled: false,
    minimumRequiredOffers: 3,
    abnormalLowOfferRatio: 0.7,
    acceptableRiskThreshold: 60,
    createdAt: "2025-03-20",
    updatedAt: "2025-06-29",
  },
  {
    id: "deal-medical-devices",
    organizationId: "org-health-ministry",
    reference: "2025/177",
    title: "توريد أجهزة طبية للمستشفيات",
    description: "اقتناء وتركيب أجهزة تصوير ومراقبة للعديد من المؤسسات الاستشفائية.",
    type: "توريد",
    sector: "التجهيزات الطبية",
    region: "وطني",
    estimatedValue: 680000000,
    currency: "DZD",
    status: "receiving_offers",
    publishedAt: "2025-06-05",
    submissionDeadline: "2025-07-20",
    openingDate: "2025-07-21",
    isPublic: true,
    aiEnabled: false,
    smartMatchingEnabled: false,
    minimumRequiredOffers: 4,
    abnormalLowOfferRatio: 0.72,
    acceptableRiskThreshold: 55,
    createdAt: "2025-05-25",
    updatedAt: "2025-06-30",
  },
  {
    id: "deal-bridge",
    organizationId: "org-health-projects",
    reference: "2025/176",
    title: "إنشاء جسر على طريق رئيسي",
    description: "أشغال إنجاز جسر وربطه بالطريق الولائي مع منشآت السلامة والتصريف.",
    type: "أشغال",
    sector: "البناء والأشغال العمومية",
    region: "بومرداس",
    estimatedValue: 1250000000,
    currency: "DZD",
    status: "delayed",
    publishedAt: "2025-02-10",
    submissionDeadline: "2025-03-20",
    openingDate: "2025-03-22",
    evaluationStartDate: "2025-03-28",
    awardDate: "2025-05-02",
    executionStartDate: "2025-06-01",
    executionEndDate: "2026-12-01",
    isPublic: true,
    aiEnabled: false,
    smartMatchingEnabled: false,
    minimumRequiredOffers: 3,
    abnormalLowOfferRatio: 0.68,
    acceptableRiskThreshold: 50,
    createdAt: "2025-01-30",
    updatedAt: "2025-06-27",
  },
  {
    id: "deal-water-maintenance",
    organizationId: "org-health-projects",
    reference: "2025/175",
    title: "خدمات صيانة وتشغيل محطات المياه",
    description: "خدمات دورية لتشغيل وصيانة محطات المياه والتجهيزات الملحقة بها.",
    type: "خدمات",
    sector: "الخدمات والصيانة",
    region: "قسنطينة",
    estimatedValue: 210000000,
    currency: "DZD",
    status: "temporary_award",
    publishedAt: "2025-01-12",
    submissionDeadline: "2025-02-20",
    openingDate: "2025-02-21",
    evaluationStartDate: "2025-02-24",
    awardDate: "2025-04-10",
    isPublic: true,
    aiEnabled: false,
    smartMatchingEnabled: false,
    minimumRequiredOffers: 3,
    abnormalLowOfferRatio: 0.7,
    acceptableRiskThreshold: 50,
    createdAt: "2025-01-02",
    updatedAt: "2025-06-22",
  },
  {
    id: "deal-school-furniture",
    organizationId: "org-health-ministry",
    reference: "2025/174",
    title: "توريد أثاث وتجهيزات للمدارس",
    description: "توريد مكاتب وكراسي وخزائن وتجهيزات تعليمية لفائدة المؤسسات المدرسية.",
    type: "توريد",
    sector: "التجهيزات واللوازم",
    region: "وطني",
    estimatedValue: 155000000,
    currency: "DZD",
    status: "completed",
    publishedAt: "2025-01-05",
    submissionDeadline: "2025-02-05",
    openingDate: "2025-02-06",
    evaluationStartDate: "2025-02-10",
    awardDate: "2025-03-02",
    executionStartDate: "2025-03-15",
    executionEndDate: "2025-05-15",
    isPublic: true,
    aiEnabled: false,
    smartMatchingEnabled: false,
    minimumRequiredOffers: 3,
    abnormalLowOfferRatio: 0.7,
    acceptableRiskThreshold: 60,
    createdAt: "2024-12-28",
    updatedAt: "2025-05-20",
  },
];

const commonRequirements = [
  "السجل التجاري",
  "شهادة الضرائب",
  "شهادة CNAS / CASNOS",
  "التصنيف والتأهيل المهني",
  "المراجع المهنية",
];

export const dealRequirements: DealRequirement[] = deals.flatMap((deal) =>
  commonRequirements.map((title, index) => ({
    id: `req-${deal.id}-${index + 1}`,
    dealId: deal.id,
    title,
    description: "وثيقة إلزامية للتحقق من أهلية المتعامل الاقتصادي.",
    requirementType: index < 3 ? "administrative" : "technical",
    isRequired: true,
    allowedFileTypes: ["pdf"],
    maxFileSizeMb: 20,
    orderIndex: index + 1,
  })),
);

export const dealDocuments: DealDocument[] = deals.flatMap((deal) => [
  {
    id: `doc-${deal.id}-cahier`,
    dealId: deal.id,
    title: "دفتر الشروط",
    documentType: "cahier_des_charges",
    filePath: `deal-documents/${deal.organizationId}/${deal.id}/cahier-des-charges.pdf`,
    fileName: "cahier-des-charges.pdf",
    visibility: "public",
    status: "active",
    createdAt: deal.publishedAt ?? deal.createdAt,
  },
  {
    id: `doc-${deal.id}-opening`,
    dealId: deal.id,
    title: "محضر الفتح",
    documentType: "opening_minutes",
    filePath: `deal-documents/${deal.organizationId}/${deal.id}/opening-minutes.pdf`,
    fileName: "opening-minutes.pdf",
    visibility: "internal",
    status: "active",
    createdAt: deal.openingDate ?? deal.createdAt,
  },
]);

const stageNames = [
  "الإعلان",
  "استقبال العروض",
  "الفتح",
  "التقييم التقني",
  "التقييم المالي",
  "المنح المؤقت",
  "الطعون",
  "المنح النهائي",
  "التنفيذ",
  "الاستلام",
  "الإغلاق",
];

export const dealStages: DealStage[] = deals.flatMap((deal) =>
  stageNames.map((name, index) => {
    const completedCount =
      deal.status === "completed" ? 11 : deal.status === "delayed" ? 8 : deal.status === "technical_evaluation" ? 3 : 2;
    const status = index < completedCount ? "completed" : index === completedCount ? "in_progress" : "not_started";

    return {
      id: `stage-${deal.id}-${index + 1}`,
      dealId: deal.id,
      name,
      status: deal.status === "delayed" && index === completedCount ? "delayed" : status,
      startedAt: index < completedCount + 1 ? "2025-04-01" : undefined,
      endedAt: index < completedCount ? "2025-04-10" : undefined,
      dueAt: new Date(new Date(deal.submissionDeadline).getTime() + index * 1000 * 60 * 60 * 24 * 10)
        .toISOString()
        .slice(0, 10),
      responsibleName: index < 5 ? "مصلحة الصفقات" : "لجنة التقييم",
      notes: index === completedCount ? "تحتاج متابعة يومية لتفادي التأخر." : "لا توجد ملاحظات حرجة.",
      orderIndex: index + 1,
    };
  }),
);

export const evaluationCriteria: EvaluationCriterion[] = deals.flatMap((deal) => [
  {
    id: `criteria-${deal.id}-technical`,
    dealId: deal.id,
    title: "المنهجية والوسائل",
    criteriaType: "technical",
    weight: 40,
    maxScore: 100,
  },
  {
    id: `criteria-${deal.id}-experience`,
    dealId: deal.id,
    title: "الخبرة والمراجع",
    criteriaType: "technical",
    weight: 30,
    maxScore: 100,
  },
  {
    id: `criteria-${deal.id}-price`,
    dealId: deal.id,
    title: "العرض المالي",
    criteriaType: "financial",
    weight: 30,
    maxScore: 100,
  },
]);

export const applications: Application[] = [
  {
    id: "app-health-future",
    dealId: "deal-health-center",
    operatorId: "op-future",
    status: "under_evaluation",
    technicalScore: 82,
    financialScore: 76,
    totalScore: 80.2,
    proposedAmount: 398000000,
    proposedDurationDays: 330,
    submittedAt: "2025-05-12",
    isWinner: false,
    missingDocuments: 0,
  },
  {
    id: "app-health-modern",
    dealId: "deal-health-center",
    operatorId: "op-modern-build",
    status: "missing_documents",
    technicalScore: 69,
    financialScore: 88,
    totalScore: 74.7,
    proposedAmount: 292000000,
    proposedDurationDays: 300,
    submittedAt: "2025-05-14",
    isWinner: false,
    missingDocuments: 1,
  },
  {
    id: "app-medical-inmaa",
    dealId: "deal-medical-devices",
    operatorId: "op-inmaa",
    status: "submitted",
    proposedAmount: 641000000,
    proposedDurationDays: 90,
    submittedAt: "2025-06-24",
    isWinner: false,
    missingDocuments: 0,
  },
  {
    id: "app-bridge-haditha",
    dealId: "deal-bridge",
    operatorId: "op-haditha",
    status: "winner",
    technicalScore: 91,
    financialScore: 79,
    totalScore: 87.4,
    proposedAmount: 1190000000,
    proposedDurationDays: 520,
    submittedAt: "2025-03-18",
    isWinner: true,
    missingDocuments: 0,
  },
  {
    id: "app-water-rawad",
    dealId: "deal-water-maintenance",
    operatorId: "op-rawad",
    status: "winner",
    technicalScore: 77,
    financialScore: 83,
    totalScore: 78.8,
    proposedAmount: 167000000,
    proposedDurationDays: 365,
    submittedAt: "2025-02-18",
    isWinner: true,
    missingDocuments: 0,
  },
  {
    id: "app-furniture-ahd",
    dealId: "deal-school-furniture",
    operatorId: "op-ahd",
    status: "not_winner",
    technicalScore: 63,
    financialScore: 72,
    totalScore: 65.7,
    proposedAmount: 143000000,
    proposedDurationDays: 60,
    submittedAt: "2025-02-02",
    isWinner: false,
    missingDocuments: 0,
  },
];

export const applicationDocuments: ApplicationDocument[] = applications.flatMap((application) =>
  dealRequirements
    .filter((requirement) => requirement.dealId === application.dealId)
    .slice(0, 4)
    .map((requirement, index) => ({
      id: `adoc-${application.id}-${index + 1}`,
      applicationId: application.id,
      requirementId: requirement.id,
      title: requirement.title,
      fileName: `${requirement.title}.pdf`,
      status: application.missingDocuments > 0 && index === 2 ? "missing" : "uploaded",
      reviewNotes: index === 2 && application.missingDocuments > 0 ? "النسخة المرفوعة غير مكتملة." : undefined,
    })),
);

export const operatorDocuments: OperatorDocument[] = [
  {
    id: "opdoc-1",
    operatorId: "op-future",
    title: "السجل التجاري",
    documentType: "commercial_register",
    fileName: "registre-commerce.pdf",
    issueDate: "2024-01-10",
    expiryDate: "2027-01-10",
    status: "valid",
  },
  {
    id: "opdoc-2",
    operatorId: "op-future",
    title: "شهادة الضرائب",
    documentType: "tax_certificate",
    fileName: "tax-certificate.pdf",
    issueDate: "2025-01-01",
    expiryDate: "2025-08-15",
    status: "expiring",
  },
  {
    id: "opdoc-3",
    operatorId: "op-future",
    title: "شهادة CNAS",
    documentType: "social_security",
    fileName: "cnas.pdf",
    issueDate: "2025-02-01",
    expiryDate: "2026-02-01",
    status: "valid",
  },
  {
    id: "opdoc-4",
    operatorId: "op-future",
    title: "شهادة التأهيل",
    documentType: "classification",
    fileName: "classification.pdf",
    issueDate: "2023-05-20",
    expiryDate: "2025-05-20",
    status: "expired",
  },
];

export const transparencyScores: TransparencyScore[] = [
  {
    dealId: "deal-health-center",
    documentsScore: 84,
    deadlinesScore: 72,
    competitionScore: 66,
    evaluationScore: 78,
    justificationScore: 74,
    publicationScore: 92,
    totalScore: 77,
    calculatedAt: "2025-06-29",
  },
  {
    dealId: "deal-medical-devices",
    documentsScore: 91,
    deadlinesScore: 88,
    competitionScore: 54,
    evaluationScore: 70,
    justificationScore: 68,
    publicationScore: 95,
    totalScore: 78,
    calculatedAt: "2025-06-30",
  },
  {
    dealId: "deal-bridge",
    documentsScore: 72,
    deadlinesScore: 41,
    competitionScore: 62,
    evaluationScore: 73,
    justificationScore: 48,
    publicationScore: 86,
    totalScore: 63,
    calculatedAt: "2025-06-27",
  },
  {
    dealId: "deal-water-maintenance",
    documentsScore: 69,
    deadlinesScore: 70,
    competitionScore: 39,
    evaluationScore: 75,
    justificationScore: 52,
    publicationScore: 80,
    totalScore: 64,
    calculatedAt: "2025-06-22",
  },
  {
    dealId: "deal-school-furniture",
    documentsScore: 86,
    deadlinesScore: 90,
    competitionScore: 74,
    evaluationScore: 81,
    justificationScore: 79,
    publicationScore: 90,
    totalScore: 83,
    calculatedAt: "2025-05-20",
  },
];

export const riskAlerts: RiskAlert[] = [
  {
    id: "risk-weak-competition",
    dealId: "deal-water-maintenance",
    operatorId: "op-rawad",
    applicationId: "app-water-rawad",
    riskType: "ضعف المنافسة",
    severity: "high",
    score: 75,
    reason: "عدد المتنافسين أقل من الحد الأدنى المحدد للصفقة.",
    evidence: { applications_count: 1, minimum_required_offers: 3 },
    recommendation: "تمديد آجال الإعلان أو توسيع النشر إن كان ذلك ممكناً.",
    status: "open",
    generatedBy: "rules",
    createdAt: "2025-06-22",
  },
  {
    id: "risk-low-offer",
    dealId: "deal-health-center",
    operatorId: "op-modern-build",
    applicationId: "app-health-modern",
    riskType: "عرض منخفض بشكل غير طبيعي",
    severity: "medium",
    score: 55,
    reason: "العرض المالي أقل من متوسط العروض بنسبة معتبرة.",
    evidence: { proposed_amount: 292000000, reference_average: 345000000 },
    recommendation: "طلب تبريرات كتابية قبل استكمال التقييم المالي.",
    status: "reviewing",
    generatedBy: "rules",
    createdAt: "2025-06-18",
  },
  {
    id: "risk-avenants",
    dealId: "deal-bridge",
    operatorId: "op-haditha",
    applicationId: "app-bridge-haditha",
    riskType: "كثرة الملاحق",
    severity: "critical",
    score: 88,
    reason: "نسبة الزيادة التعاقدية تجاوزت 20% مع تأخر في الإنجاز.",
    evidence: { avenants_count: 4, increase_percentage: 24, delay_days: 45 },
    recommendation: "إحالة الملف للمراجعة الداخلية قبل المصادقة على أي ملحق إضافي.",
    status: "open",
    generatedBy: "rules",
    createdAt: "2025-06-26",
  },
  {
    id: "risk-delay",
    dealId: "deal-bridge",
    riskType: "تأخرات غير مبررة",
    severity: "high",
    score: 79,
    reason: "تجاوز في الآجال يفوق 30 يوماً دون وثائق تبريرية كافية.",
    evidence: { delay_days: 45, threshold: 30 },
    recommendation: "تحديث مخطط التنفيذ وربط كل تمديد بوثيقة مبررة.",
    status: "open",
    generatedBy: "rules",
    createdAt: "2025-06-27",
  },
];

export const avenants: Avenant[] = [
  {
    id: "avenant-bridge-1",
    dealId: "deal-bridge",
    title: "ملحق تعديل كميات الخرسانة",
    type: "مالي وتقني",
    oldAmount: 1190000000,
    newAmount: 1340000000,
    increasePercentage: 12.6,
    reason: "تعديل الكميات بعد الدراسات التنفيذية.",
    riskImpact: "medium",
  },
  {
    id: "avenant-bridge-2",
    dealId: "deal-bridge",
    title: "ملحق تمديد آجال",
    type: "آجال",
    oldAmount: 1340000000,
    newAmount: 1475000000,
    increasePercentage: 10.1,
    oldDeadline: "2026-12-01",
    newDeadline: "2027-02-15",
    reason: "تأخر تحويل الشبكات التقنية.",
    riskImpact: "high",
  },
];

export const executionTracking: ExecutionTracking[] = [
  {
    id: "exec-bridge",
    dealId: "deal-bridge",
    title: "أشغال المنشأة الرئيسية",
    description: "تنفيذ الركائز والجسور المعدنية والتهيئة المحيطة.",
    progressPercentage: 42,
    status: "delayed",
    plannedStart: "2025-06-01",
    plannedEnd: "2026-12-01",
    delayDays: 45,
    notes: "تحتاج اللجنة إلى تبرير مفصل للتأخر.",
  },
  {
    id: "exec-school",
    dealId: "deal-school-furniture",
    title: "توريد وتجهيز",
    description: "توريد الأثاث والتجهيزات للمؤسسات المدرسية.",
    progressPercentage: 100,
    status: "completed",
    plannedStart: "2025-03-15",
    plannedEnd: "2025-05-15",
    delayDays: 0,
    notes: "اكتمل التنفيذ دون تحفظات جوهرية.",
  },
];

export const notifications: Notification[] = [
  {
    id: "notif-1",
    recipientType: "operator",
    title: "آخر أجل قريب",
    body: "صفقة توريد أجهزة طبية تغلق باب التقديم خلال أقل من 20 يوماً.",
    type: "warning",
    entityType: "deal",
    entityId: "deal-medical-devices",
    isRead: false,
    createdAt: "2025-06-30",
  },
  {
    id: "notif-2",
    recipientType: "operator",
    title: "وثيقة تحتاج تحديث",
    body: "شهادة التأهيل منتهية ويجب استبدالها قبل استعمالها في ملف جديد.",
    type: "danger",
    entityType: "operator_document",
    entityId: "opdoc-4",
    isRead: false,
    createdAt: "2025-06-29",
  },
  {
    id: "notif-3",
    recipientType: "institution",
    title: "تنبيه خطر مرتفع",
    body: "تم تسجيل تنبيه كثرة الملاحق في صفقة إنشاء الجسر.",
    type: "danger",
    entityType: "risk_alert",
    entityId: "risk-avenants",
    isRead: false,
    createdAt: "2025-06-27",
  },
];

export const reports: Report[] = [
  {
    id: "report-1",
    title: "تقرير الشفافية الشهري",
    reportType: "transparency",
    status: "generated",
    createdAt: "2025-06-30",
  },
  {
    id: "report-2",
    title: "تقرير مخاطر الصفقات المفتوحة",
    reportType: "risk",
    status: "generated",
    createdAt: "2025-06-29",
  },
  {
    id: "report-3",
    title: "تقرير أداء المتعاملين",
    reportType: "operators",
    status: "draft",
    createdAt: "2025-06-21",
  },
];

export const auditLogs: AuditLog[] = [
  {
    id: "audit-1",
    userName: "أمينة بن سالم",
    organizationId: "org-health-projects",
    entityType: "deal",
    entityId: "deal-health-center",
    action: "publish",
    summary: "نشر صفقة إنجاز مركز صحي متعدد الخدمات.",
    createdAt: "2025-04-01T09:10:00Z",
  },
  {
    id: "audit-2",
    userName: "كمال عابد",
    organizationId: "org-health-projects",
    entityType: "application",
    entityId: "app-health-modern",
    action: "mark_missing_documents",
    summary: "تسجيل نقص في وثيقة شهادة CNAS.",
    createdAt: "2025-06-18T13:45:00Z",
  },
  {
    id: "audit-3",
    userName: "نادية مرابط",
    organizationId: "org-health-projects",
    entityType: "risk_alert",
    entityId: "risk-avenants",
    action: "open_review",
    summary: "فتح مراجعة داخلية لتنبيه كثرة الملاحق.",
    createdAt: "2025-06-27T11:20:00Z",
  },
];

export function getOrganizationById(id: string) {
  return organizations.find((organization) => organization.id === id);
}

export function getDealById(id: string) {
  return deals.find((deal) => deal.id === id);
}

export function getOperatorById(id: string) {
  return operators.find((operator) => operator.id === id);
}

export function getApplicationsByDealId(dealId: string) {
  return applications.filter((application) => application.dealId === dealId);
}

export function getApplicationsByOperatorId(operatorId: string) {
  return applications.filter((application) => application.operatorId === operatorId);
}

export function getRequirementsByDealId(dealId: string) {
  return dealRequirements.filter((requirement) => requirement.dealId === dealId);
}

export function getDocumentsByDealId(dealId: string) {
  return dealDocuments.filter((document) => document.dealId === dealId);
}

export function getStagesByDealId(dealId: string) {
  return dealStages.filter((stage) => stage.dealId === dealId).sort((a, b) => a.orderIndex - b.orderIndex);
}

export function getTransparencyByDealId(dealId: string) {
  return transparencyScores.find((score) => score.dealId === dealId);
}

export function getRiskAlertsByDealId(dealId: string) {
  return riskAlerts.filter((alert) => alert.dealId === dealId);
}

export function getApplicationById(id: string) {
  return applications.find((application) => application.id === id);
}

export function getApplicationDocuments(applicationId: string) {
  return applicationDocuments.filter((document) => document.applicationId === applicationId);
}
